import type { Person } from "schema-dts";

export const personSchema: Person = {
  "@type": "Person",
  name: "Nirjan Khadka",
  url: "https://nirjan.dev/about",
  knowsAbout: [
    "web development",
    "web design",
    "web accessibility",
    "web performance",
    "web optimization",
    "web development tools",
    "web performance optimization",
    "web accessibility",
    "web development",
    "TypeScript",
    "JavaScript",
    "HTML",
    "CSS",
    "Golang",
    "Vue.js",
    "Svelte.js",
    "Astro.js",
    "Node.js",
    "SQL",
    "PostgreSQL",
    "SQLite",
    "Docker",
    "Linux",
    "Git",
    "Tailwind CSS",
    "UI/UX",
    "Design Systems",
    "Design Tokens",
  ],

  image: "https://nirjan.dev/images/profile.png",
  email: "hi@nirjan.dev",
  sameAs: [
    "https://github.com/nirjan-dev",
    "https://bsky.app/profile/nirjan.dev",
    "https://linkedin.com/in/nirjankhadka",
  ],
  gender: "male",
  jobTitle: "Fullstack Product Developer",
  description:
    "Building apps on the web that are fast, user friendly, accessible and secure. I work with Typescript, React.js, Svelte, Golang, Postgres and SQLite",
};
